//! DeskBuddy Windows widget — M3: multi-server, data-driven floating card.
//!
//! Standard Rust GUI setup (`eframe`/`egui`, 0.36): a `BuddyApp` that owns
//! the shared `WidgetState` (one `BuddyState` per inference server), a
//! background `poller` thread feeding it from `GET /slots` (hot) + `/props`
//! (once) + `/metrics` (slow) **per server**, and a borderless translucent
//! card that stacks the servers vertically (top = first).
//!
//! The server list and poll cadence come from a **config file** (see
//! `config.rs`) so adding a server is an edit, not a recompile. The window
//! grows vertically to fit however many servers are configured (one 320-wide
//! row each).
//!
//! The card has two **display modes** (`WidgetState::display_mode`, shared
//! across all rows):
//!   * **Data** (default) — one row per server, chosen by that server's
//!     `BuddyState::phase()` (generating / prompting / idle / down): status
//!     dot + big number left, model + capacity right, leftover line, tok/s
//!     sparkline + session footnote, dim host footer.
//!   * **Scene** — the full card becomes pixel art ("Plumber's run") showing
//!     **combined activity**: one band per server, stacked, each in its own
//!     phase (busy sprints, calm level when idle, piranha plant when down)
//!     — blits
//!     of the generated bitmaps in `scene_assets` (see `shared/scene-assets/`).
//!
//! The mode is toggled by **clicking anywhere on the card content** (the
//! drag strip and the close × are not content); the right-click menu on the
//! close button offers it explicitly too.
#![windows_subsystem = "windows"]
use eframe::egui;
use eframe::egui::viewport::ViewportCommand;
use std::sync::{Arc, Mutex};

mod buddy_state;
mod config;
mod poller;
/// AUTO-GENERATED — do not edit: scene bitmaps for scene mode (see
/// `shared/scene-assets/`). Generated by `shared/scene-assets/render_scene.py`.
#[path = "../../shared/scene-assets/bitmaps/widget/scene_assets.rs"]
mod scene_assets;

use buddy_state::{DisplayMode, Phase, SharedState, WidgetState};

// Card palette — straight from the approved design (WINDOWS_WIDGET_SPEC.md):
// dark translucent card, white ink, muted/dim grays, one teal accent. The
// window is transparent and `Visuals` are forced dark, so these constants are
// the whole theme — the card renders identically in every system theme.
const CARD_BG: egui::Color32 = egui::Color32::from_rgba_unmultiplied_const(30, 30, 34, 209); // rgba(30,30,34,0.82)
const CARD_BORDER: egui::Color32 = egui::Color32::from_rgba_unmultiplied_const(255, 255, 255, 28); // rgba(255,255,255,0.11)
const DOWN_BORDER: egui::Color32 = egui::Color32::from_rgba_unmultiplied_const(224, 86, 86, 102); // rgba(224,86,86,0.4)
const INK: egui::Color32 = egui::Color32::from_rgb(242, 243, 245); // #f2f3f5
const MUTED: egui::Color32 = egui::Color32::from_rgb(154, 160, 170); // #9aa0aa
const DIM: egui::Color32 = egui::Color32::from_rgb(95, 101, 111); // #5f656f
const ACCENT: egui::Color32 = egui::Color32::from_rgb(78, 201, 176); // #4ec9b0
const GEN_DOT: egui::Color32 = egui::Color32::from_rgb(78, 201, 120); // #4ec978
const PROMPTING: egui::Color32 = egui::Color32::from_rgb(230, 180, 80); // #e6b450
const IDLE_DOT: egui::Color32 = egui::Color32::from_rgb(122, 128, 138); // #7a808a
const DOWN: egui::Color32 = egui::Color32::from_rgb(224, 86, 86); // #e05656
const ROW_SEP: egui::Color32 = egui::Color32::from_rgba_unmultiplied_const(255, 255, 255, 24); // rgba(255,255,255,0.09)
const CORNER_RADIUS: f32 = 14.0;
/// Chrome geometry: size and margin of the close button (top-right corner).
const CHROME_BTN: f32 = 20.0;
const CHROME_MARG: f32 = 8.0;
/// Extra gap between the data card's model text and the close button, so the
/// text never visually crowds (or runs under) the corner chrome.
const CHROME_TEXT_GAP: f32 = 8.0;
/// Height of the top drag strip (the "drag-and-drop pane").
const DRAG_STRIP_H: f32 = 22.0;
/// Card width, fixed (the 2:1 level grid fits it).
pub const CARD_W: f32 = 320.0;
/// The chrome/drag-strip band reserved above the first server row.
const HEADER_H: f32 = 34.0;
/// One 320-wide server row (data card): enough for dot+number+sublabel,
/// leftover, sparkline+footnote, and the dim host footer.
const ROW_H: f32 = 176.0;
/// Gap between server rows.
const ROW_GAP: f32 = 10.0;
/// Bottom padding below the last row (kept small: each row's content is
/// vertically centered in its slot, so only the same slack as a row offset).
const FOOT_PAD: f32 = 6.0;

/// The window height for `n` stacked server rows (scales with the config).
pub fn card_height(n: usize) -> f32 {
    let n = n.max(1);
    HEADER_H + (n as f32) * ROW_H + ((n - 1) as f32) * ROW_GAP + FOOT_PAD
}

fn mono(size: f32) -> egui::FontId {
    egui::FontId::new(size, egui::FontFamily::Monospace)
}

/// Truncate `text` with a leading ellipsis so it fits within `max_width`,
/// measured with the context's text layout. Shaves from the START so a
/// right-aligned column keeps its tail visible (e.g. "160k ctx · Q4_K -
/// Medium" → "…Q4_K - Medium").
fn fit_text(ctx: &egui::Context, text: &str, font: egui::FontId, max_width: f32) -> String {
    let width_of = |s: &str| {
        let g = ctx
            .fonts_mut(|f| f.layout_no_wrap(s.to_string(), font.clone(), egui::Color32::WHITE));
        (*g).rect.width()
    };
    if width_of(text) <= max_width {
        return text.to_string();
    }
    let chars: Vec<char> = text.chars().collect();
    let mut cut = 0;
    while cut < chars.len() && width_of(&format!("…{}", chars[cut..].iter().collect::<String>())) > max_width {
        cut += 1;
    }
    if cut >= chars.len() {
        "…".to_string()
    } else {
        format!("…{}", chars[cut..].iter().collect::<String>())
    }
}

/// Color of the big number per phase (design §States).
fn number_color(st: &buddy_state::BuddyState) -> egui::Color32 {
    match st.phase() {
        Phase::Generating => ACCENT,
        Phase::Prompting => PROMPTING,
        Phase::Idle => INK,
        Phase::Down => DIM,
    }
}

/// A short label for a context window: `160000 -> "160k"`, `4096 -> "4k"`.
fn fmt_ctx(tokens: u64) -> String {
    if tokens >= 1_000_000 {
        format!("{:.0}M", tokens as f64 / 1_000_000.0)
    } else if tokens >= 1000 {
        format!("{:.0}k", tokens as f64 / 1000.0)
    } else {
        tokens.to_string()
    }
}

/// A short tok/s rate: `1980 -> "2.0k"`, `127 -> "127"`, `17_000 -> "17.0k"`.
fn fmt_rate(tps: f64) -> String {
    if tps >= 1000.0 {
        format!("{:.1}k", tps / 1000.0)
    } else {
        format!("{:.0}", tps)
    }
}

/// A single model-name font size that fits **every** row at once. Each row's
/// model name differs in length, and picking per-row sizes made the shorter
/// name render larger than the longer one — an inconsistent look. This returns
/// the largest size in the (descending) `sizes` ladder at which the longest
/// name still fits `max_width`, so all rows share one size. If even the
/// smallest size can't fit the longest name, it returns that smallest size and
/// the caller ellipsizes.
fn uniform_font_size(
    ctx: &egui::Context,
    names: &[Option<String>],
    sizes: &[f32],
    max_width: f32,
) -> f32 {
    let width_of = |s: &str, size: f32| {
        let g = ctx.fonts_mut(|f| {
            f.layout_no_wrap(
                s.to_string(),
                egui::FontId::new(size, egui::FontFamily::Monospace),
                egui::Color32::WHITE,
            )
        });
        (*g).rect.width()
    };
    for &size in sizes {
        let all_fit = names.iter().all(|n| {
            n.as_deref()
                .map(|s| width_of(s, size) <= max_width)
                .unwrap_or(true)
        });
        if all_fit {
            return size;
        }
    }
    *sizes.last().unwrap_or(&sizes[0])
}

/// `(big_number, sublabel, dot_color)` for the current phase.
fn headline(st: &buddy_state::BuddyState) -> (String, String, egui::Color32) {
    match st.phase() {
        Phase::Generating => (
            format!("{:.0}", st.toks_per_s),
            "tok/s".to_string(),
            GEN_DOT,
        ),
        Phase::Prompting => match st.prefill_frac {
            Some(frac) => {
                let rate = if st.prefill_tps > 0.0 {
                    format!("prompting · {} tok/s", fmt_rate(st.prefill_tps))
                } else {
                    "prompting…".to_string()
                };
                (format!("{:.0}%", frac * 100.0), rate, PROMPTING)
            }
            None => ("···".to_string(), "prompting…".to_string(), PROMPTING),
        },
        Phase::Idle => ("—".to_string(), "idle".to_string(), IDLE_DOT),
        Phase::Down => ("--".to_string(), "server down".to_string(), DOWN),
    }
}

/// Remaining-work / phase-status line (design: a fixed row in every state).
fn remaining_line(st: &buddy_state::BuddyState) -> (String, egui::Color32) {
    match st.phase() {
        Phase::Generating => {
            if st.n_remain > 0 {
                let toks = st.n_remain.to_string();
                return match st.eta_secs() {
                    Some(eta) => (format!("~{eta:.0}s left · {toks} tok"), INK),
                    None => (format!("{toks} tok left"), INK),
                };
            }
            ("generating · no bound".to_string(), MUTED)
        }
        Phase::Prompting => ("processing prompt".to_string(), MUTED),
        Phase::Idle => ("loaded · ready".to_string(), DIM),
        Phase::Down => ("retrying in 5 s".to_string(), DOWN),
    }
}

/// Session footnote: "avg 121 · 92% cached". Only from the slow `/metrics`
/// path; hidden entirely when we have no data yet.
fn footnote(st: &buddy_state::BuddyState) -> Option<String> {
    let mut parts = Vec::new();
    if let Some(avg) = st.session_avg_tps {
        if avg > 0.0 {
            parts.push(format!("avg {avg:.0}"));
        }
    }
    if let Some(r) = st.kv_reuse {
        parts.push(format!("{:.0}% cached", r * 100.0));
    }
    if let Some(r) = st.spec_acceptance {
        parts.push(format!("spec {:.0}%", r * 100.0));
    }
    match parts.len() {
        0 => None,
        _ => Some(parts.join(" · ")),
    }
}

/// The capacity line — muted second line of the right column. When the live
/// context occupancy is known (`/slots` `n_prompt_tokens`):
/// `72k/160k · 45% · Q4_K - Medium`; without it, the static
/// `160k ctx · Q4_K - Medium`. The parallel slot count (`/slots` length)
/// leads as a `×N slots` chip when known, so capacity + concurrency read
/// together: `×2 · 72k/160k · 45% · Q4_K - Medium`. `(text, warning)` — the
/// warning flag turns the line amber when the context is past ~80% full.
fn capacity_line(st: &buddy_state::BuddyState) -> Option<(String, bool)> {
    let quant = st.quant.as_deref();
    let (ctx_part, warn) = match (st.ctx_used, st.ctx_tokens, st.ctx_usage()) {
        (Some(used), Some(total), Some(ratio)) if total > 0 => (
            format!("{}/{} · {:.0}%", fmt_ctx(used), fmt_ctx(total), ratio * 100.0),
            ratio >= 0.8,
        ),
        (_, Some(total), _) => (format!("{} ctx", fmt_ctx(total)), false),
        _ => (String::new(), false),
    };
    let mut parts: Vec<String> = Vec::new();
    if let Some(n) = st.n_slots {
        parts.push(format!("×{n} slots"));
    }
    if !ctx_part.is_empty() {
        parts.push(ctx_part);
    }
    if let Some(q) = quant {
        parts.push(q.to_string());
    }
    match parts.len() {
        0 => None,
        _ => Some((parts.join(" · "), warn)),
    }
}

struct BuddyApp {
    state: SharedState,
    /// Where (in screen-local px) the user grabbed the drag strip, if a
    /// card-drag is in progress.
    drag_grab: Option<egui::Pos2>,
}

impl BuddyApp {
    fn new(cc: &eframe::CreationContext<'_>) -> Self {
        cc.egui_ctx.set_theme(egui::ThemePreference::Dark);
        let mut v = egui::Visuals::dark();
        v.window_fill = egui::Color32::TRANSPARENT;
        v.extreme_bg_color = egui::Color32::TRANSPARENT;
        cc.egui_ctx.set_visuals(v);

        // Screenshot-test mode: `DESKBUDDY_SCENE` seeds a deterministic,
        // fully-stacked `WidgetState` and skips the poller (see
        // `tests/screenshot_test.rs`). `DESKBUDDY_LIVE_SERVER=<host>` (parity
        // P4) instead seeds the same state from the LIVE server so a capture
        // reads what the device is reading at the same moment. Without
        // either, load the config and start the per-server poller before the
        // first frame.
        let state: SharedState = if let Ok(host) = std::env::var("DESKBUDDY_LIVE_SERVER") {
            Arc::new(Mutex::new(live_widget(&host).expect("live_widget always builds state")))
        } else {
            match std::env::var("DESKBUDDY_SCENE") {
                Ok(name) => {
                    let ws = scene_widget(&name).expect("scene handled in main");
                    Arc::new(Mutex::new(ws))
                }
                Err(_) => {
                    let cfg = config::load();
                    let state: SharedState = Arc::new(Mutex::new(poller::initial_state(&cfg)));
                    poller::spawn_poller(Arc::clone(&state), cc.egui_ctx.clone(), cfg);
                    state
                }
            }
        };
        Self { state, drag_grab: None }
    }
}

impl eframe::App for BuddyApp {
    fn ui(&mut self, ui: &mut egui::Ui, _frame: &mut eframe::Frame) {
        let capturing = std::env::var_os("EFRAME_SCREENSHOT_TO").is_some();
        if capturing {
            ui.ctx().request_repaint();
        }

        egui::CentralPanel::default()
            .frame(egui::Frame::NONE)
            .show(ui, |ui| {
                let ws = self.state.lock().unwrap().clone();
                let screen = ui.ctx().viewport_rect();

                // The card background: a rounded translucent rect filling the
                // window (the window is transparent, so only the card shows).
                // Border tints red when EVERY server is down.
                {
                    let painter = ui.painter();
                    let all_down = !ws.servers.is_empty()
                        && ws.servers.iter().all(|s| s.phase() == Phase::Down);
                    let border = if all_down { DOWN_BORDER } else { CARD_BORDER };
                    painter.rect(
                        screen,
                        CORNER_RADIUS,
                        CARD_BG,
                        egui::Stroke::new(1.0, border),
                        egui::StrokeKind::Inside,
                    );
                }

                // Two display modes. Scene swaps the whole card for pixel art.
                if ws.display_mode == DisplayMode::Scene {
                    draw_scene(ui, &ws, screen, capturing);
                } else {
                    draw_data_card(ui, &ws, screen);
                }
                // Top chrome (drag strip + close ×) — drawn last so it sits
                // above both modes and owns its corner.
                draw_chrome(ui, &self.state, &mut self.drag_grab);

                // **Click-to-toggle**: a click anywhere on the card CONTENT
                // (below the drag strip, off the close button) flips the
                // shared display mode data ⇄ scene. `primary_clicked()`
                // already filters out drags (release too far / too slow from
                // the press), so dragging the strip never toggles.
                let close = chrome_button(screen);
                let strip_bottom = screen.top() + DRAG_STRIP_H;
                let (clicked, pos) = ui.ctx().input(|i| {
                    (i.pointer.primary_clicked(), i.pointer.interact_pos())
                });
                if let Some(_p) =
                    pos.filter(|p| p.y > strip_bottom && !close.contains(*p))
                {
                    if clicked {
                        self.state.lock().unwrap().toggle_mode();
                    }
                }
            });
    }
}

/// The top-right **close ×** button rect (the only chrome button), shared by
/// `draw_chrome` and the data card so the model text can be anchored to clear
/// of it.
fn chrome_button(screen: egui::Rect) -> egui::Rect {
    let right = screen.right() - CHROME_MARG;
    let top = screen.top() + CHROME_MARG;
    egui::Rect::from_min_max(
        egui::pos2(right - CHROME_BTN, top),
        egui::pos2(right, top + CHROME_BTN),
    )
}

/// Top chrome, shared by both display modes:
/// * a **drag strip** across the top of the card (a visible grip at the left;
///   press-and-drag anywhere in the strip moves the window);
/// * a **close ×** button (the visible "window close").
/// The data ⇄ scene mode is NOT a button — it toggles on a **click anywhere
/// on the card content** (see `BuddyApp::ui`). Right-clicking the close ×
/// offers mode switch + Quit.
fn draw_chrome(ui: &mut egui::Ui, state: &SharedState, drag: &mut Option<egui::Pos2>) {
    let screen = ui.ctx().viewport_rect();
    let close = chrome_button(screen);
    let strip = egui::Rect::from_min_max(
        egui::pos2(screen.left() + 2.0, screen.top() + 1.0),
        egui::pos2(close.left() - 6.0, screen.top() + DRAG_STRIP_H),
    );
    let painter = ui.painter();
    let hover = ui.ctx().input(|i| i.pointer.hover_pos());

    for rect in [strip, close] {
        let hovered = hover.map_or(false, |p| rect.contains(p));
        let (fill, border, radius) = match rect {
            r if r == close => (
                if hovered {
                    egui::Color32::from_rgb(70, 74, 84)
                } else {
                    egui::Color32::from_rgb(48, 52, 60)
                },
                egui::Color32::from_rgb(150, 155, 168),
                6.0,
            ),
            _ => (
                if hovered {
                    egui::Color32::from_rgba_unmultiplied(255, 255, 255, 36)
                } else {
                    egui::Color32::from_rgba_unmultiplied(255, 255, 255, 14)
                },
                egui::Color32::TRANSPARENT,
                0.0,
            ),
        };
        painter.rect(rect, radius, fill, egui::Stroke::new(1.0, border), egui::StrokeKind::Inside);
    }

    // Drag grip: three short horizontal lines, top-left of the strip.
    let grip_c = egui::pos2(strip.left() + 11.0, screen.top() + 10.0);
    let grip_stroke = egui::Stroke::new(1.5, egui::Color32::from_rgb(150, 154, 165));
    for dy in [-3.0_f32, 0.0, 3.0] {
        painter.line_segment(
            [
                egui::pos2(grip_c.x - 4.0, grip_c.y + dy),
                egui::pos2(grip_c.x + 4.0, grip_c.y + dy),
            ],
            grip_stroke,
        );
    }

    // Close glyph: an ×.
    let c = close.center();
    let o = 3.5;
    let x = egui::Stroke::new(2.0, MUTED);
    painter.line_segment([egui::pos2(c.x - o, c.y - o), egui::pos2(c.x + o, c.y + o)], x);
    painter.line_segment([egui::pos2(c.x - o, c.y + o), egui::pos2(c.x + o, c.y - o)], x);

    // --- Drag the window by the strip (egui honors StartDrag on press edge).
    if let Some(pointer) = hover {
        let in_strip = strip.contains(pointer);
        let pressed = ui.ctx().input(|i| i.pointer.primary_down());
        if in_strip && pressed && drag.is_none() {
            *drag = Some(pointer);
            ui.ctx().send_viewport_cmd(ViewportCommand::StartDrag);
        } else if !in_strip || !pressed {
            *drag = None;
        }
    } else {
        *drag = None;
    }

    // --- Close × click + right-click menu (mode switch + Quit).
    let cresp = ui.interact(close, egui::Id::new("close_btn"), egui::Sense::click());
    if cresp.clicked() {
        ui.ctx().send_viewport_cmd(ViewportCommand::Close);
    }
    let _ = cresp.context_menu(|ui| {
        ui.set_min_width(150.0);
        ui.heading(egui::RichText::new("DeskBuddy").size(12.0));
        ui.separator();
        if ui.button("Switch to scene mode").clicked() {
            state.lock().unwrap().set_mode(DisplayMode::Scene);
            ui.close();
        }
        if ui.button("Switch to data card").clicked() {
            state.lock().unwrap().set_mode(DisplayMode::Data);
            ui.close();
        }
        if ui.button("Quit").clicked() {
            ui.ctx().send_viewport_cmd(ViewportCommand::Close);
            ui.close();
        }
    });
}

/// Scene mode ("Plumber's run"): the full card becomes pixel art showing
/// **combined activity** — one band per server, stacked, each in its own
/// phase. The bands are blits of the **generated bitmaps** in the
/// `scene_assets` module (one 320×320 image per state; regenerated by
/// `shared/scene-assets/render_scene.py`, see `shared/scene-assets/README.md`)
/// — the widget ships images, not a procedural painter.
fn draw_scene(ui: &mut egui::Ui, ws: &WidgetState, screen: egui::Rect, capturing: bool) {
    let painter = ui.painter();
    // Region below the top chrome.
    let region = egui::Rect::from_min_max(
        egui::pos2(screen.left(), screen.top() + DRAG_STRIP_H + 6.0),
        egui::pos2(screen.right(), screen.bottom()),
    );
    let bands = scene_band_rects(ws.servers.len(), region);
    let images = scene_images(ui.ctx());
    for (i, band) in bands.iter().enumerate() {
        let phase = ws.servers[i].phase();
        let idx = match phase {
            Phase::Generating => 0,
            Phase::Prompting => 1,
            Phase::Idle => 2,
            Phase::Down => 3,
        };
        painter.image(
            images[idx].id(),
            *band,
            egui::Rect::from_min_max(egui::pos2(0.0, 0.0), egui::pos2(1.0, 1.0)),
            egui::Color32::WHITE,
        );
    }

    // Per-server label + status dot beside each band. The bands span the
    // region edge-to-edge, so the badges are anchored to the region's right
    // edge (label text ~24pt + dot) instead of the band's right edge.
    let bx = region.right() - 46.0;
    for (i, band) in bands.iter().enumerate() {
        let phase = ws.servers[i].phase();
        let color = match phase {
            Phase::Generating => GEN_DOT,
            Phase::Prompting => PROMPTING,
            Phase::Idle => IDLE_DOT,
            Phase::Down => DOWN,
        };
        let cy = band.center().y;
        painter.circle_filled(egui::pos2(bx, cy), 3.5, color);
        let label = ws.labels.get(i).cloned().unwrap_or_else(|| format!("srv{}", i + 1));
        painter.text(
            egui::pos2(bx + 8.0, cy),
            egui::Align2::LEFT_CENTER,
            label,
            mono(11.0),
            MUTED,
        );
    }

    if !capturing {
        // The bitmaps are static; repaint on the old 8 fps cadence anyway so
        // chrome (hover/drag) and data-mode transitions feel responsive.
        ui.ctx().request_repaint_after(std::time::Duration::from_millis(125));
    }
}

/// The band rects for `n` stacked scene bands in `region` (same geometry as
/// the old procedural painter: 2:1 level, centered, 6 pt gap, inset 2 pt).
fn scene_band_rects(n: usize, region: egui::Rect) -> Vec<egui::Rect> {
    let mut bands = Vec::new();
    if n == 0 {
        return bands;
    }
    let aspect = scene_assets::SCENE_W as f32 / scene_assets::SCENE_H as f32;
    let gap: f32 = 6.0;
    let total_gap = gap * (n as f32 - 1.0);
    let band_h = ((region.height() - total_gap) / n as f32).max(24.0);
    let band_w = band_h * aspect;
    let start_y = region.top() + 2.0;
    for i in 0..n {
        let y = start_y + i as f32 * (band_h + gap);
        let x0 = region.center().x - band_w / 2.0;
        bands.push(egui::Rect::from_min_max(
            egui::pos2(x0, y),
            egui::pos2(x0 + band_w, y + band_h),
        ));
    }
    bands
}

/// The scene bitmaps, loaded once as GPU textures (working / prompting /
/// idle / down). egui 0.36's `Painter::image` takes a `TextureId`, so the
/// `ColorImage`s are uploaded via `Context::load_texture`.
fn scene_images(ctx: &egui::Context) -> [egui::TextureHandle; 4] {
    fn load(ctx: &egui::Context, name: &str, bytes: &[u8]) -> egui::TextureHandle {
        ctx.load_texture(
            name,
            egui::ColorImage::from_rgba_unmultiplied(
                [scene_assets::SCENE_W, scene_assets::SCENE_H],
                bytes,
            ),
            egui::TextureOptions::LINEAR,
        )
    }
    [
        load(ctx, "scene-working", &scene_assets::WORKING),
        load(ctx, "scene-prompting", &scene_assets::PROMPTING),
        load(ctx, "scene-idle", &scene_assets::IDLE),
        load(ctx, "scene-down", &scene_assets::DOWN),
    ]
}

/// The data card (default display mode): one row per server, stacked. Each
/// row has status dot + big number left, model + capacity right, leftover
/// line, sparkline + footnote, and a dim `label · host` footer. Rows are
/// separated by a thin rule. Everything is painted with the painter.
fn draw_data_card(ui: &mut egui::Ui, ws: &WidgetState, screen: egui::Rect) {
    let painter = ui.painter();
    let close = chrome_button(screen);

    // Row baselines: start below the header band, spaced by ROW_H + ROW_GAP.
    let first_top = screen.top() + HEADER_H;
    let left = screen.left() + 18.0;
    let right_col = close.left() - CHROME_TEXT_GAP;

    // The model name sits at the row top, above the big number (which is
    // LEFT_COL_DROP lower), so it has the full row width to itself — not the
    // narrow right column. One uniform size across all rows (largest that fits
    // the longest name) keeps the two names the same size instead of the
    // shorter one rendering bigger.
    let model_max_w = right_col - left;
    let model_size = uniform_font_size(
        ui.ctx(),
        &ws.servers.iter().map(|s| s.model.clone()).collect::<Vec<_>>(),
        &[12.0, 11.0, 10.0, 9.0, 8.0],
        model_max_w,
    );

    for (i, st) in ws.servers.iter().enumerate() {
        let row_top = first_top + i as f32 * (ROW_H + ROW_GAP);
        // Separator between rows (not above the first).
        if i > 0 {
            let sep_y = row_top - ROW_GAP / 2.0;
            painter.line_segment(
                [
                    egui::pos2(left, sep_y),
                    egui::pos2(screen.right() - 18.0, sep_y),
                ],
                egui::Stroke::new(1.0, ROW_SEP),
            );
        }
        let y = row_top + row_center_offset(st);
        // The left column sits LEFT_COL_DROP lower than the right (model +
        // capacity) block: the big number would otherwise climb into the
        // capacity line at the row top.
        let y_l = y + LEFT_COL_DROP;

        // ---- Row 1: [dot / number / sublabel]  [model + capacity] ----
        let (big, sub, dot) = headline(st);
        painter.circle_filled(egui::pos2(left + 4.0, y_l + 4.0), 4.0, dot);
        let num_rect = painter.text(
            egui::pos2(left, y_l + 14.0),
            egui::Align2::LEFT_TOP,
            big,
            mono(40.0),
            number_color(st),
        );
        let sub_y = y_l + 14.0 + num_rect.height() + 2.0;
        painter.text(
            egui::pos2(left + 1.0, sub_y),
            egui::Align2::LEFT_TOP,
            sub,
            mono(13.0),
            MUTED,
        );

        // Right column: model name + muted capacity, RIGHT-aligned, anchored
        // to the corner chrome buttons so long names never run under them.
        if let Some(name) = st.model.clone() {
            // Uniform size (computed once for all rows, above) so the names
            // never differ in size; the name has the full row width at its Y.
            // Ellipsize only as a last resort.
            let name = fit_text(ui.ctx(), &name, mono(model_size), model_max_w);
            let name_rect = painter.text(
                egui::pos2(right_col, y),
                egui::Align2::RIGHT_TOP,
                name,
                mono(model_size),
                INK,
            );
            if let Some((cap, cap_warn)) = capacity_line(st) {
                let cap = fit_text(ui.ctx(), &cap, mono(10.5), right_col - left);
                painter.text(
                    egui::pos2(right_col, y + name_rect.height() + 2.0),
                    egui::Align2::RIGHT_TOP,
                    cap,
                    mono(10.5),
                    if cap_warn { PROMPTING } else { MUTED },
                );
            }
        }

        // ---- Row 2: remaining work / phase status ----
        let (left_text, left_col) = remaining_line(st);
        let left_rect = painter.text(
            egui::pos2(left, sub_y + 20.0),
            egui::Align2::LEFT_TOP,
            left_text,
            mono(12.0),
            left_col,
        );

        // ---- Row 3: tok/s sparkline (left) + session footnote (hidden when
        // down). The footnote is kept short so it never crowds the sparkline.
        if st.phase() != Phase::Down {
            if let Some(f) = footnote(st) {
                let fy = sub_y + 20.0 + left_rect.height() + 6.0;
                let f_rect = painter.text(
                    egui::pos2(left + 64.0, fy),
                    egui::Align2::LEFT_TOP,
                    f,
                    mono(10.5),
                    MUTED,
                );
                let hist = st.rate_history();
                if !hist.is_empty() {
                    let max = hist.iter().cloned().fold(0.0f64, f64::max).max(1.0);
                    let nb = hist.len().min(10);
                    let (bar_w, bar_gap) = (3.0, 2.0);
                    let bottom = fy + f_rect.height() - 1.0;
                    for (bi, &v) in hist.iter().skip(hist.len().saturating_sub(nb)).enumerate() {
                        let bh = (13.0 * (v / max) as f32).max(3.0);
                        let x = left + 2.0 + bi as f32 * (bar_w + bar_gap);
                        painter.rect_filled(
                            egui::Rect::from_min_max(
                                egui::pos2(x, bottom - bh),
                                egui::pos2(x + bar_w, bottom),
                            ),
                            1.0,
                            ACCENT,
                        );
                    }
                }
            }
        }

        // ---- Row 4: dim host footer (`label · host` left, session `NNk
        // total` right, both on the same baseline). ----
        let footer_y = sub_y + 20.0 + left_rect.height() + 6.0 + footnote_row_height(st) + 4.0;
        let label = ws.labels.get(i).cloned().unwrap_or_else(|| format!("srv{}", i + 1));
        painter.text(
            egui::pos2(left, footer_y),
            egui::Align2::LEFT_TOP,
            footer_text(&label, st),
            mono(9.5),
            DIM,
        );
        if let Some(t) = st.tokens_total {
            if t > 0 {
                painter.text(
                    egui::pos2(screen.right() - 18.0, footer_y),
                    egui::Align2::RIGHT_TOP,
                    format!("{} total", fmt_ctx(t)),
                    mono(9.5),
                    DIM,
                );
            }
        }
    }
}

/// Vertical drop of the left column (dot + number + its stacked lines) so
/// the big 40 pt number clears the right column's model + capacity lines,
/// which start at the row top. The right block is top-anchored; the left
/// block sits a line lower.
const LEFT_COL_DROP: f32 = 10.0;

/// Vertical centering of a row's content block inside its `ROW_H` slot, so
/// the row's text doesn't sit glued to the slot's top edge with dead space
/// below. `row_content_h` is the block's (fixed-font) height from the dot to
/// the footer, per phase.
fn row_center_offset(st: &buddy_state::BuddyState) -> f32 {
    (ROW_H - row_content_h(st)) / 2.0
}

/// Estimated rendered height of one row's content (dot → footer). Font sizes
/// are fixed, so this is stable; the down/no-metrics layout is shorter.
fn row_content_h(st: &buddy_state::BuddyState) -> f32 {
    if st.phase() == Phase::Down || footnote(st).is_none() {
        121.0
    } else {
        137.0
    }
}

/// Approximate height of the sparkline+footnote row for vertical layout.
fn footnote_row_height(st: &buddy_state::BuddyState) -> f32 {
    if st.phase() == Phase::Down || footnote(st).is_none() {
        0.0
    } else {
        16.0
    }
}

/// The per-server footer: `label · host` (left side of the dim footer row;
/// the right-aligned session `NNk total` is drawn at the call site).
fn footer_text(label: &str, st: &buddy_state::BuddyState) -> String {
    let host = st.host_label.clone().unwrap_or_else(|| "—".to_string());
    format!("{label} · {host}")
}

/// The four phases the card can show, as deterministic, fully-seeded states
/// for the screenshot tests (spec: one golden PNG per phase).
pub const SCENES: &[&str] = &["generating", "prompting", "idle", "down"];

/// A fixed sparkline profile (the design's bar heights, normalized 0..1).
const SCENE_SPARK: &[f64] = &[0.36, 0.57, 0.5, 0.86, 1.0, 0.79, 0.64, 0.93, 1.0];

/// Build a fully-determined, two-server `WidgetState` for a named scene.
/// Both servers share the same `DESKBUDDY_SCENE` phase so the stacked rows
/// (and the combined scene bands) are deterministic for the goldens.
fn scene_widget(name: &str) -> Option<WidgetState> {
    let make = |host: &str| -> Option<buddy_state::BuddyState> {
        let mut s = buddy_state::BuddyState::default();
        s.model = Some("Qwen3.8-27B-UD-Q4_K_XL".to_string());
        s.quant = Some("Q4_K - Medium".to_string());
        s.ctx_tokens = Some(160_000);
        s.ctx_used = Some(71_883); // ~45% of the window (live /slots figure)
        s.n_slots = Some(2); // live server exposes two parallel slots
        s.host_label = Some(host.to_string());
        s.feed_metrics(121.0, 9_200, 10_000, 2_875, 4_062, 50_000);
        s.set_rate_hist(SCENE_SPARK.iter().map(|&v| 100.0 * v).collect());
        s.conn = buddy_state::ConnState::Up;
        match name {
            "generating" => {
                s.working = true;
                s.decoded = 4_200;
                s.toks_per_s = 127.4;
                s.n_remain = 1_847;
            }
            "prompting" => {
                s.working = true;
                s.decoded = 0;
                s.n_remain = -1;
                s.prefill_frac = Some(0.42); // ~42% into the prompt
                s.prefill_tps = 1_980.0; // ~2.0k tok/s live prefill rate
            }
            "idle" => {}
            "down" => s.feed_error(),
            _ => return None,
        }
        Some(s)
    };
    let ws = WidgetState {
        servers: vec![make("m.tower1:11444")?, make("m.mini1:11444")?],
        labels: vec!["tower1".to_string(), "mini1".to_string()],
        display_mode: if std::env::var("DESKBUDDY_MODE").as_deref() == Ok("scene") {
            DisplayMode::Scene
        } else {
            DisplayMode::Data
        },
    };
    Some(ws)
}

fn live_widget(host: &str) -> Option<WidgetState> {
    use crate::poller;
    let mk = || {
        let mut s = buddy_state::BuddyState::default();
        s.host_label = Some(host.to_string());
        if let Ok((model, quant, ctx)) = poller::fetch_props(host) {
            s.feed_props(model, quant, ctx);
        }
        if let Ok((avg, cached, total, spec_a, spec_d, predicted)) = poller::fetch_metrics(host) {
            s.feed_metrics(avg, cached, total, spec_a, spec_d, predicted);
        }
        // Two /slots snapshots ~800 ms apart give a live rate with the same
        // Δ(tokens)/Δ(real elapsed) math as the poller — so the captured
        // frame shows a real number when the server is mid-generation.
        let snap = |s: &mut buddy_state::BuddyState, elapsed: std::time::Duration| match poller::fetch_slots(host) {
            Ok((working, decode, remain, ctx_used, n_ctx, pf, pt, n_slots)) => {
                s.feed_ok(working, decode, remain, ctx_used, n_ctx, pf, pt, elapsed);
                s.feed_slots_count(n_slots);
                (working, decode)
            }
            Err(e) => {
                eprintln!("[buddy] live /slots failed for {host}: {e}");
                s.feed_error();
                (false, 0)
            }
        };
        snap(&mut s, std::time::Duration::from_millis(2000));
        std::thread::sleep(std::time::Duration::from_millis(800));
        snap(&mut s, std::time::Duration::from_millis(800));
        s
    };
    let ws = WidgetState {
        servers: vec![mk(), mk()],
        labels: vec!["tower1".to_string(), "mini1".to_string()],
        display_mode: crate::buddy_state::DisplayMode::Data,
    };
    Some(ws)
}

fn main() -> eframe::Result {
    // Screenshot-test mode: validate the scene up front so a bad name fails
    // fast with a clear message instead of a half-built window.
    if let Some(name) = std::env::var_os("DESKBUDDY_SCENE") {
        let name = name.to_string_lossy();
        if scene_widget(&name).is_none() {
            eprintln!("unknown DESKBUDY_SCENE {name:?}; expected one of {SCENES:?}");
            std::process::exit(2);
        }
    }

    // Window size scales with the number of configured servers. In screenshot
    // mode (scene OR live) the size is fixed to the default (two servers).
    let n = if std::env::var_os("DESKBUDDY_SCENE").is_some()
        || std::env::var_os("DESKBUDDY_LIVE_SERVER").is_some()
    {
        2
    } else {
        config::load().servers.len().max(1)
    };
    let h = card_height(n);

    let native_options = eframe::NativeOptions {
        viewport: egui::viewport::ViewportBuilder::default()
            .with_title("DeskBuddy")
            .with_inner_size([CARD_W, h])
            .with_min_inner_size([CARD_W, h])
            .with_max_inner_size([CARD_W, h])
            .with_decorations(false)
            .with_always_on_top()
            .with_transparent(true),
        ..Default::default()
    };

    eframe::run_native("DeskBuddy", native_options, Box::new(|cc| {
        cc.egui_ctx.set_pixels_per_point(2.0);
        Ok(Box::new(BuddyApp::new(cc)))
    }))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn scene_widget_rejects_unknown_name() {
        assert!(scene_widget("nonsense").is_none());
    }

    #[test]
    fn scene_widget_builds_each_known_scene() {
        for name in SCENES {
            assert!(scene_widget(name).is_some(), "scene {name:?} should build");
        }
    }
}
