#!/usr/bin/env python
"""Generate shared/net_config.h from shared/net.env (single source of truth).

Both ESP32 firmwares include <net_config.h>:
  - esp32c6_480x480/firmware (WiFi + /slots poller)
  - esp32s3_272x792/fw/test_sketch (net status page)
Compile flag (arduino-cli):  --include C:/Users/.../desk-buddy/shared

Usage: python shared/tools/net_config.py
"""
import os

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))  # repo root
ENV = os.path.join(ROOT, 'shared', 'net.env')
OUT = os.path.join(ROOT, 'shared', 'net_config.h')

def load_env(path):
    if not os.path.exists(path):
        raise SystemExit(
            f"{path} not found - copy shared/net.env.example to net.env and fill in values")
    vals = {}
    for line in open(path, encoding='utf-8'):
        line = line.split('#', 1)[0].strip()
        if '=' in line:
            k, v = line.split('=', 1)
            vals[k.strip()] = v.strip()
    return vals

cfg = load_env(ENV)
missing = [k for k in ('WIFI_SSID', 'WIFI_PSWD', 'LAN_HOST', 'LAN_PORT',
                       'WEATHER_HOST', 'WEATHER_LAT', 'WEATHER_LON') if not cfg.get(k)]
if missing:
    raise SystemExit(f"shared/net.env missing values: {missing}")

# Second inference server (srv2). Falls back to the primary endpoint when not
# set, so firmwares that only know LAN_HOST/LAN_PORT still build unchanged.
lan2_host = cfg.get('LAN2_HOST') or cfg['LAN_HOST']
lan2_port = cfg.get('LAN2_PORT') or cfg['LAN_PORT']

hdr = f"""// AUTO-GENERATED by shared/tools/net_config.py from shared/net.env
// Shared desk-buddy network config (WiFi creds + LAN endpoint).
// Do not edit by hand - edit shared/net.env and re-run the generator.
#ifndef NET_CONFIG_H
#define NET_CONFIG_H

#define WIFI_SSID "{cfg['WIFI_SSID']}"
#define WIFI_PSWD "{cfg['WIFI_PSWD']}"
#define LAN_HOST  "{cfg['LAN_HOST']}"
#define LAN_PORT  {cfg['LAN_PORT']}
// Second inference server (srv2)
#define LAN2_HOST "{lan2_host}"
#define LAN2_PORT {lan2_port}
// Weather API (Open-Meteo) — host + location (strings: used in URL paths)
#define WEATHER_HOST "{cfg['WEATHER_HOST']}"
#define WEATHER_LAT  "{cfg['WEATHER_LAT']}"
#define WEATHER_LON  "{cfg['WEATHER_LON']}"

#endif // NET_CONFIG_H
"""
with open(OUT, 'w', newline='\n') as f:
    f.write(hdr)
print(f'wrote {OUT} (ssid={cfg["WIFI_SSID"]}, host={cfg["LAN_HOST"]}:{cfg["LAN_PORT"]}, '
      f'host2={lan2_host}:{lan2_port})')
