#!/usr/bin/env python3
"""Generate fw/test_sketch/le_dercainfo.h — Let's Encrypt trust anchors as DER.

WHY DER, NOT PEM:
  The prebuilt esp32-arduino-libs (idf-release_v5.5, platform 3.3.3) that this
  board compiles against has a PEM parser that rejects the Let's Encrypt chain
  PEMs (mbedtls_x509_crt_parse -> MBEDTLS_ERR_X509_BAD_INPUT_DATA, -0x2180)
  even though the host openssl parses the identical bytes, and even though the
  SAME lib's mbedtls_x509_crt_parse_der accepts the identical cert as DER. The
  Arduino WiFiClientSecure wrapper feeds PEM, so its verified TLS to
  api.open-meteo.com can never work on this build. Feeding DER trust anchors
  directly to mbedTLS (fw/test_sketch uses raw mbedTLS) verifies cleanly
  (handshake OK, verify flags 0x00000000).

The server sends:  leaf(open-meteo.com) <- YR1 <- Root YR <- ISRG Root X1.
We embed the trust roots the client needs: ISRG Root X1 + YR1 (both DER).
The server supplies the rest of the chain, so this is a full verification.

Recapture the chain (the device may see a different chain than the dev box):
  openssl s_client -connect api.open-meteo.com:443 -servername api.open-meteo.com -showcerts
Convert each intermediate/root PEM you need to DER:
  openssl x509 -in cert.pem -outform DER -out cert.der
Then:  python tools/gen_le_dercainfo.py  x1.der  yr1.der   (order = emit order)

Rotating: re-run when the embedded intermediates expire (X1: 2035, YR1: 2028).
"""
import os, subprocess, sys

DEV = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))   # esp32s3_272x792/
OUT = os.path.join(DEV, 'fw', 'test_sketch', 'le_dercainfo.h')


def der_bytes(der_path):
    if der_path.lower().endswith('.der'):
        return open(der_path, 'rb').read()
    # accept .pem: convert via openssl
    der = der_path[:-4] + '.der' if der_path.lower().endswith('.pem') else der_path + '.der'
    subprocess.run(['openssl', 'x509', '-in', der_path, '-outform', 'DER', '-out', der],
                   check=True, capture_output=True)
    return open(der, 'rb').read()


def c_array(name, b):
    line = ', '.join(hex(x) for x in b)
    return f'static const uint8_t {name}[] = {{ {line} }};'


def main(der_paths):
    names = ['LE_CA_%d' % i for i in range(len(der_paths))]
    blocks = [c_array(n, der_bytes(p)) for n, p in zip(names, der_paths)]
    entry = ',\n'.join('  { %s, sizeof(%s) }' % (n, n) for n in names)
    hdr = (
        '// AUTO-GENERATED by tools/gen_le_dercainfo.py -- do not edit by hand.\n'
        "// Let's Encrypt trust anchors (DER) for WEATHER_HOST (open-meteo.com).\n"
        '// DER, not PEM: this esp32-arduino build\'s PEM parser rejects the LE\n'
        '// chain PEMs (BAD_INPUT_DATA); its DER parser + raw mbedTLS verify\n'
        "// cleanly. Server sends leaf <- YR1 <- Root YR <- ISRG Root X1; we\n"
        '// trust the roots, the server supplies the intermediates.\n'
        '#ifndef LE_DERCINFO_H\n'
        '#define LE_DERCINFO_H\n\n'
        '#include <stdint.h>\n\n'
        + '\n'.join(blocks) + '\n\n'
        'struct le_anchor { const uint8_t *der; size_t len; };\n'
        'static const struct le_anchor LE_ANCHORS[] = {\n'
        + entry + '\n};\n'
        '#endif // LE_DERCINFO_H\n'
    )
    with open(OUT, 'w', newline='\n') as f:
        f.write(hdr)
    print('wrote', OUT, len(hdr), 'bytes', '(%d anchors)' % len(der_paths))


if __name__ == '__main__':
    if len(sys.argv) < 2:
        raise SystemExit('usage: gen_le_dercainfo.py <anchor.der|.pem> [...]')
    main(sys.argv[1:])
