#!/usr/bin/env python
"""Generate fw/test_sketch/le_cainfo.h from the captured Let's Encrypt chain.

DEPRECATED — see gen_le_dercainfo.py. This PEM-based header does NOT work on
this board's prebuilt esp32-arduino-libs (idf-release_v5.5 / 3.3.3): its
mbedtls PEM parser rejects the chain with MBEDTLS_ERR_X509_BAD_INPUT_DATA
while its DER parser works. The firmware now uses le_dercainfo.h (DER).

The ESP32's built-in CA store only has ISRG Root X1. open-meteo.com's server
sends leaf <- YR1 <- Root YR (cross-signed by ISRG Root X1) but NOT the root,
so both intermediates must be trust anchors. Recapture with:

  openssl s_client -connect api.open-meteo.com:443 -servername api.open-meteo.com -showcerts < /dev/null

then point the two args at the intermediate + cross-signed root PEMs.
"""
import os

DEV = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))  # esp32s3_272x792/
OUT = os.path.join(DEV, 'fw', 'test_sketch', 'le_cainfo.h')

def c_string(pem):
    # PEM -> a valid single C string literal. Newlines are required by the
    # PEM format (mbedtls's parser looks for newline-terminated markers), so
    # keep them — emit each as a \n escape. One physical line in the .h file.
    body = pem.strip()
    body = body.replace('\\', '\\\\').replace('"', '\\"')
    body = body.replace('\r\n', '\n').replace('\n', '\\n')
    return '"' + body + '"'

def main(chain_pems):
    blocks = [c_string(open(p).read()) for p in chain_pems]
    hdr = (
        "// AUTO-GENERATED by tools/gen_le_cainfo.py — do not edit by hand.\n"
        "// Let's Encrypt chain anchors for WEATHER_HOST (open-meteo.com):\n"
        "// the server sends leaf <- YR1 <- Root YR (cross-signed by ISRG Root\n"
        "// X1) but not the root, and the ESP32 built-in store only has ISRG\n"
        "// Root X1 — so both intermediates must be added as trust anchors.\n"
        f"// Captured from the live TLS chain (2026-09-26). Rotate when it expires:\n"
        "//   openssl s_client -connect api.open-meteo.com:443 -servername api.open-meteo.com\n"
        "#ifndef LE_CAINFO_H\n"
        "#define LE_CAINFO_H\n\n"
        "static const char LE_CAINFO[] PROGMEM =\n"
        + "\n".join(blocks) + "\n;\n\n"
        "#endif // LE_CAINFO_H\n"
    )
    with open(OUT, 'w', newline='\n') as f:
        f.write(hdr)
    print('wrote', OUT, len(hdr), 'bytes')

if __name__ == '__main__':
    import sys
    if len(sys.argv) < 2:
        raise SystemExit('usage: gen_le_cainfo.py <anchor1.pem> [anchor2.pem ...]')
    main(sys.argv[1:])
